# comments explain how this file was prepared
# 
# lib:
# - start with list of files currently in vtest/lib
# - find then in the varnish-cache tree
#   for f in $(cat /tmp/lib) ; do find . -name $f ; done | tee /tmp/f
#   this has one too many ./tools/coccinelle/vdef.h (manually removed)
# - for those, create the list
#   <file>
#   <file>==>lib/<basename>
# - in addition, find all renames:
#   for f in $(cat /tmp/f) ; do echo ; echo $f ; echo ---------- ; git log --name-status --diff-filter=R --follow -- $f ; done | awk '/^R/ { print $2 }'
# - manually check the renames
#   for f in $(cat /tmp/f) ; do echo ; echo $f ; echo ---------- ; git log --oneline --name-only --follow -- $f ; done
include/miniobj.h
include/miniobj.h==>lib/miniobj.h
lib/libvarnish/vas.c
lib/libvarnish/vas.c==>lib/vas.c
include/vas.h
include/vas.h==>lib/vas.h
lib/libvarnish/vav.c
lib/libvarnish/vav.c==>lib/vav.c
include/vav.h
include/vav.h==>lib/vav.h
lib/libvarnish/vbh.c
lib/libvarnish/vbh.c==>lib/vbh.c
include/vbh.h
include/vbh.h==>lib/vbh.h
include/vcli.h
include/vcli.h==>lib/vcli.h
lib/libvarnish/vct.c
lib/libvarnish/vct.c==>lib/vct.c
include/vct.h
include/vct.h==>lib/vct.h
include/vdef.h
include/vdef.h==>lib/vdef.h
include/vend.h
include/vend.h==>lib/vend.h
lib/libvarnish/vev.c
lib/libvarnish/vev.c==>lib/vev.c
include/vev.h
include/vev.h==>lib/vev.h
lib/libvarnish/vfil.c
lib/libvarnish/vfil.c==>lib/vfil.c
include/vfil.h
include/vfil.h==>lib/vfil.h
lib/libvarnish/vfl.c
lib/libvarnish/vfl.c==>lib/vfl.c
include/vfl.h
include/vfl.h==>lib/vfl.h
lib/libvgz/vgz.h
lib/libvgz/vgz.h==>lib/vgz.h
lib/libvarnish/vjsn.c
lib/libvarnish/vjsn.c==>lib/vjsn.c
include/vjsn.h
include/vjsn.h==>lib/vjsn.h
lib/libvarnish/vlu.c
lib/libvarnish/vlu.c==>lib/vlu.c
include/vlu.h
include/vlu.h==>lib/vlu.h
lib/libvarnish/vnum.c
lib/libvarnish/vnum.c==>lib/vnum.c
include/vnum.h
include/vnum.h==>lib/vnum.h
lib/libvarnish/vpf.c
lib/libvarnish/vpf.c==>lib/vpf.c
include/vpf.h
include/vpf.h==>lib/vpf.h
include/vqueue.h
include/vqueue.h==>lib/vqueue.h
lib/libvarnish/vre.c
lib/libvarnish/vre.c==>lib/vre.c
include/vre.h
include/vre.h==>lib/vre.h
include/vre_pcre2.h
include/vre_pcre2.h==>lib/vre_pcre2.h
lib/libvarnish/vrnd.c
lib/libvarnish/vrnd.c==>lib/vrnd.c
include/vrnd.h
include/vrnd.h==>lib/vrnd.h
lib/libvarnish/vsa.c
lib/libvarnish/vsa.c==>lib/vsa.c
include/vsa.h
include/vsa.h==>lib/vsa.h
lib/libvarnish/vsb.c
lib/libvarnish/vsb.c==>lib/vsb.c
include/vsb.h
include/vsb.h==>lib/vsb.h
include/vapi/vsig.h
include/vapi/vsig.h==>lib/vapi/vsig.h
lib/libvarnish/vss.c
lib/libvarnish/vss.c==>lib/vss.c
include/vss.h
include/vss.h==>lib/vss.h
lib/libvarnish/vsub.c
lib/libvarnish/vsub.c==>lib/vsub.c
include/vsub.h
include/vsub.h==>lib/vsub.h
lib/libvarnish/vtcp.c
lib/libvarnish/vtcp.c==>lib/vtcp.c
include/vtcp.h
include/vtcp.h==>lib/vtcp.h
lib/libvarnish/vtim.c
lib/libvarnish/vtim.c==>lib/vtim.c
include/vtim.h
include/vtim.h==>lib/vtim.h
lib/libvarnish/vus.c
lib/libvarnish/vus.c==>lib/vus.c
include/vus.h
include/vus.h==>lib/vus.h
# previous names of files in lib/ (see top comment)
# manually removed because of failed git copy heuristic:
# - bin/varnishd/cache_acceptor.h
# manually removed because "too much history"
# - include/libvarnish.h
lib/libvarnish/assert.c
lib/libvarnish/argv.c
include/argv.h
include/cli.h
lib/libvarnish/vtmpfile.c
lib/libvarnish/flopen.c
include/flopen.h
lib/libvgz/zlib.h
lib/libvarnishapi/vjsn.c
lib/libvarnishapi/vjsn.h
lib/libvarnish/num.c
lib/libvarnishcompat/srandomdev.c
lib/libcompat/srandomdev.c
include/sbuf.h
lib/libvarnish/subproc.c
lib/libvarnish/tcp.c
bin/varnishd/tcp.c
lib/libvarnish/time.c
lib/libvarnishapi/instance.c
#
# src/
# in varnish-cache:bin/varnishtest
# - git ls-files| grep -Ev 'tests/|flint|Make'
# create file list + rename
# deliberately include varnish-specific files vtc_varnish.c vtc_vsm.c for
# integrity with other changes
bin/varnishtest/cmds.h
bin/varnishtest/cmds.h==>src/cmds.h
bin/varnishtest/gensequences
bin/varnishtest/gensequences==>src/gensequences
bin/varnishtest/hpack.h
bin/varnishtest/hpack.h==>src/hpack.h
bin/varnishtest/huffman_gen.py
bin/varnishtest/huffman_gen.py==>src/huffman_gen.py
bin/varnishtest/huffman_input
bin/varnishtest/huffman_input==>src/huffman_input
bin/varnishtest/sequences
bin/varnishtest/sequences==>src/sequences
bin/varnishtest/teken.3
bin/varnishtest/teken.3==>src/teken.3
bin/varnishtest/teken.c
bin/varnishtest/teken.c==>src/teken.c
bin/varnishtest/teken.h
bin/varnishtest/teken.h==>src/teken.h
bin/varnishtest/teken_scs.h
bin/varnishtest/teken_scs.h==>src/teken_scs.h
bin/varnishtest/teken_subr.h
bin/varnishtest/teken_subr.h==>src/teken_subr.h
bin/varnishtest/teken_subr_compat.h
bin/varnishtest/teken_subr_compat.h==>src/teken_subr_compat.h
bin/varnishtest/teken_wcwidth.h
bin/varnishtest/teken_wcwidth.h==>src/teken_wcwidth.h
bin/varnishtest/vtc.c
bin/varnishtest/vtc.c==>src/vtc.c
bin/varnishtest/vtc.h
bin/varnishtest/vtc.h==>src/vtc.h
bin/varnishtest/vtc_barrier.c
bin/varnishtest/vtc_barrier.c==>src/vtc_barrier.c
bin/varnishtest/vtc_client.c
bin/varnishtest/vtc_client.c==>src/vtc_client.c
bin/varnishtest/vtc_gzip.c
bin/varnishtest/vtc_gzip.c==>src/vtc_gzip.c
bin/varnishtest/vtc_h2_enctbl.h
bin/varnishtest/vtc_h2_enctbl.h==>src/vtc_h2_enctbl.h
bin/varnishtest/vtc_h2_hpack.c
bin/varnishtest/vtc_h2_hpack.c==>src/vtc_h2_hpack.c
bin/varnishtest/vtc_h2_priv.h
bin/varnishtest/vtc_h2_priv.h==>src/vtc_h2_priv.h
bin/varnishtest/vtc_h2_stattbl.h
bin/varnishtest/vtc_h2_stattbl.h==>src/vtc_h2_stattbl.h
bin/varnishtest/vtc_h2_tbl.c
bin/varnishtest/vtc_h2_tbl.c==>src/vtc_h2_tbl.c
bin/varnishtest/vtc_haproxy.c
bin/varnishtest/vtc_haproxy.c==>src/vtc_haproxy.c
bin/varnishtest/vtc_http.c
bin/varnishtest/vtc_http.c==>src/vtc_http.c
bin/varnishtest/vtc_http.h
bin/varnishtest/vtc_http.h==>src/vtc_http.h
bin/varnishtest/vtc_http2.c
bin/varnishtest/vtc_http2.c==>src/vtc_http2.c
bin/varnishtest/vtc_log.c
bin/varnishtest/vtc_log.c==>src/vtc_log.c
bin/varnishtest/vtc_log.h
bin/varnishtest/vtc_log.h==>src/vtc_log.h
bin/varnishtest/vtc_logexp.c
bin/varnishtest/vtc_logexp.c==>src/vtc_logexp.c
bin/varnishtest/vtc_main.c
bin/varnishtest/vtc_main.c==>src/vtc_main.c
bin/varnishtest/vtc_misc.c
bin/varnishtest/vtc_misc.c==>src/vtc_misc.c
bin/varnishtest/vtc_process.c
bin/varnishtest/vtc_process.c==>src/vtc_process.c
bin/varnishtest/vtc_proxy.c
bin/varnishtest/vtc_proxy.c==>src/vtc_proxy.c
bin/varnishtest/vtc_server.c
bin/varnishtest/vtc_server.c==>src/vtc_server.c
bin/varnishtest/vtc_sess.c
bin/varnishtest/vtc_sess.c==>src/vtc_sess.c
bin/varnishtest/vtc_subr.c
bin/varnishtest/vtc_subr.c==>src/vtc_subr.c
bin/varnishtest/vtc_syslog.c
bin/varnishtest/vtc_syslog.c==>src/vtc_syslog.c
bin/varnishtest/vtc_tunnel.c
bin/varnishtest/vtc_tunnel.c==>src/vtc_tunnel.c
bin/varnishtest/vtc_varnish.c
bin/varnishtest/vtc_varnish.c==>src/vtc_varnish.c
bin/varnishtest/vtc_vsm.c
bin/varnishtest/vtc_vsm.c==>src/vtc_vsm.c
# src/tbl
include/tbl/h2_error.h
include/tbl/h2_error.h==>src/tbl/h2_error.h
include/tbl/h2_frames.h
include/tbl/h2_frames.h==>src/tbl/h2_frames.h
include/tbl/h2_settings.h
include/tbl/h2_settings.h==>src/tbl/h2_settings.h
include/tbl/h2_stream.h
include/tbl/h2_stream.h==>src/tbl/h2_stream.h
include/tbl/vhp_huffman.h
include/tbl/vhp_huffman.h==>src/tbl/vhp_huffman.h
include/tbl/vsig_list.h
include/tbl/vsig_list.h==>src/tbl/vsig_list.h
# tests
bin/varnishtest/tests/a00000.vtc
bin/varnishtest/tests/a00000.vtc==>tests/a00000.vtc
bin/varnishtest/tests/a00001.vtc
bin/varnishtest/tests/a00001.vtc==>tests/a00001.vtc
bin/varnishtest/tests/a00002.vtc
bin/varnishtest/tests/a00002.vtc==>tests/a00002.vtc
bin/varnishtest/tests/a00003.vtc
bin/varnishtest/tests/a00003.vtc==>tests/a00003.vtc
bin/varnishtest/tests/a00004.vtc
bin/varnishtest/tests/a00004.vtc==>tests/a00004.vtc
bin/varnishtest/tests/a00005.vtc
bin/varnishtest/tests/a00005.vtc==>tests/a00005.vtc
bin/varnishtest/tests/a00006.vtc
bin/varnishtest/tests/a00006.vtc==>tests/a00006.vtc
bin/varnishtest/tests/a00007.vtc
bin/varnishtest/tests/a00007.vtc==>tests/a00007.vtc
bin/varnishtest/tests/a00008.vtc
bin/varnishtest/tests/a00008.vtc==>tests/a00008.vtc
bin/varnishtest/tests/a00009.vtc
bin/varnishtest/tests/a00009.vtc==>tests/a00009.vtc
bin/varnishtest/tests/a00010.vtc
bin/varnishtest/tests/a00010.vtc==>tests/a00010.vtc
bin/varnishtest/tests/a00011.vtc
bin/varnishtest/tests/a00011.vtc==>tests/a00011.vtc
bin/varnishtest/tests/a00012.vtc
bin/varnishtest/tests/a00012.vtc==>tests/a00012.vtc
bin/varnishtest/tests/a00013.vtc
bin/varnishtest/tests/a00013.vtc==>tests/a00013.vtc
bin/varnishtest/tests/a00014.vtc
bin/varnishtest/tests/a00014.vtc==>tests/a00014.vtc
bin/varnishtest/tests/a00015.vtc
bin/varnishtest/tests/a00015.vtc==>tests/a00015.vtc
bin/varnishtest/tests/a00016.vtc
bin/varnishtest/tests/a00016.vtc==>tests/a00016.vtc
bin/varnishtest/tests/a00018.vtc
bin/varnishtest/tests/a00018.vtc==>tests/a00018.vtc
bin/varnishtest/tests/a00019.vtc
bin/varnishtest/tests/a00019.vtc==>tests/a00019.vtc
bin/varnishtest/tests/a00020.vtc
bin/varnishtest/tests/a00020.vtc==>tests/a00020.vtc
bin/varnishtest/tests/a00021.vtc
bin/varnishtest/tests/a00021.vtc==>tests/a00021.vtc
bin/varnishtest/tests/a00022.vtc
bin/varnishtest/tests/a00022.vtc==>tests/a00022.vtc
bin/varnishtest/tests/a00023.vtc
bin/varnishtest/tests/a00023.vtc==>tests/a00023.vtc
bin/varnishtest/tests/a00024.vtc
bin/varnishtest/tests/a00024.vtc==>tests/a00024.vtc
bin/varnishtest/tests/a00025.vtc
bin/varnishtest/tests/a00025.vtc==>tests/a00025.vtc
bin/varnishtest/tests/a00026.vtc
bin/varnishtest/tests/a00026.vtc==>tests/a00026.vtc
bin/varnishtest/tests/a00027.vtc
bin/varnishtest/tests/a00027.vtc==>tests/a00027.vtc
bin/varnishtest/tests/a02000.vtc
bin/varnishtest/tests/a02000.vtc==>tests/a02000.vtc
bin/varnishtest/tests/a02001.vtc
bin/varnishtest/tests/a02001.vtc==>tests/a02001.vtc
bin/varnishtest/tests/a02002.vtc
bin/varnishtest/tests/a02002.vtc==>tests/a02002.vtc
bin/varnishtest/tests/a02003.vtc
bin/varnishtest/tests/a02003.vtc==>tests/a02003.vtc
bin/varnishtest/tests/a02004.vtc
bin/varnishtest/tests/a02004.vtc==>tests/a02004.vtc
bin/varnishtest/tests/a02005.vtc
bin/varnishtest/tests/a02005.vtc==>tests/a02005.vtc
bin/varnishtest/tests/a02006.vtc
bin/varnishtest/tests/a02006.vtc==>tests/a02006.vtc
bin/varnishtest/tests/a02007.vtc
bin/varnishtest/tests/a02007.vtc==>tests/a02007.vtc
bin/varnishtest/tests/a02008.vtc
bin/varnishtest/tests/a02008.vtc==>tests/a02008.vtc
bin/varnishtest/tests/a02009.vtc
bin/varnishtest/tests/a02009.vtc==>tests/a02009.vtc
bin/varnishtest/tests/a02010.vtc
bin/varnishtest/tests/a02010.vtc==>tests/a02010.vtc
bin/varnishtest/tests/a02011.vtc
bin/varnishtest/tests/a02011.vtc==>tests/a02011.vtc
bin/varnishtest/tests/a02012.vtc
bin/varnishtest/tests/a02012.vtc==>tests/a02012.vtc
bin/varnishtest/tests/a02013.vtc
bin/varnishtest/tests/a02013.vtc==>tests/a02013.vtc
bin/varnishtest/tests/a02014.vtc
bin/varnishtest/tests/a02014.vtc==>tests/a02014.vtc
bin/varnishtest/tests/a02015.vtc
bin/varnishtest/tests/a02015.vtc==>tests/a02015.vtc
bin/varnishtest/tests/a02016.vtc
bin/varnishtest/tests/a02016.vtc==>tests/a02016.vtc
bin/varnishtest/tests/a02017.vtc
bin/varnishtest/tests/a02017.vtc==>tests/a02017.vtc
bin/varnishtest/tests/a02018.vtc
bin/varnishtest/tests/a02018.vtc==>tests/a02018.vtc
bin/varnishtest/tests/a02019.vtc
bin/varnishtest/tests/a02019.vtc==>tests/a02019.vtc
bin/varnishtest/tests/a02020.vtc
bin/varnishtest/tests/a02020.vtc==>tests/a02020.vtc
bin/varnishtest/tests/a02021.vtc
bin/varnishtest/tests/a02021.vtc==>tests/a02021.vtc
bin/varnishtest/tests/a02022.vtc
bin/varnishtest/tests/a02022.vtc==>tests/a02022.vtc
bin/varnishtest/tests/a02023.vtc
bin/varnishtest/tests/a02023.vtc==>tests/a02023.vtc
bin/varnishtest/tests/a02024.vtc
bin/varnishtest/tests/a02024.vtc==>tests/a02024.vtc
bin/varnishtest/tests/a02025.vtc
bin/varnishtest/tests/a02025.vtc==>tests/a02025.vtc
bin/varnishtest/tests/a02026.vtc
bin/varnishtest/tests/a02026.vtc==>tests/a02026.vtc
bin/varnishtest/tests/a02027.vtc
bin/varnishtest/tests/a02027.vtc==>tests/a02027.vtc
bin/varnishtest/tests/a02028.vtc
bin/varnishtest/tests/a02028.vtc==>tests/a02028.vtc
